// ISO 4217 World Currency List & Conversion Utilities for snapsme

export const WORLD_CURRENCIES = [
  { code: "USD", symbol: "$", name: "United States Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound Sterling" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "CAD", symbol: "CA$", name: "Canadian Dollar" },
  { code: "AUD", symbol: "AU$", name: "Australian Dollar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "CNH", symbol: "¥", name: "Offshore Chinese Yuan" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "MXN", symbol: "Mex$", name: "Mexican Peso" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "AED", symbol: "AED", name: "United Arab Emirates Dirham" },
  { code: "SAR", symbol: "SAR", name: "Saudi Riyal" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { code: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { code: "CLP", symbol: "CLP$", name: "Chilean Peso" },
  { code: "COP", symbol: "COL$", name: "Colombian Peso" },
  { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  { code: "PKR", symbol: "Rs", name: "Pakistani Rupee" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
  { code: "ARS", symbol: "ARS$", name: "Argentine Peso" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "DKK", symbol: "kr.", name: "Danish Krone" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { code: "QAR", symbol: "QR", name: "Qatari Riyal" },
  { code: "KWD", symbol: "KD", name: "Kuwaiti Dinar" },
  { code: "BHD", symbol: "BD", name: "Bahraini Dinar" },
  { code: "OMR", symbol: "OMR", name: "Omani Rial" },
  { code: "JOD", symbol: "JD", name: "Jordanian Dinar" },
  { code: "DZD", symbol: "DA", name: "Algerian Dinar" },
  { code: "MAD", symbol: "MAD", name: "Moroccan Dirham" },
  { code: "TND", symbol: "DT", name: "Tunisian Dinar" },
  { code: "LBP", symbol: "L£", name: "Lebanese Pound" },
  { code: "IQD", symbol: "IQD", name: "Iraqi Dinar" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "NPR", symbol: "Rs", name: "Nepalese Rupee" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { code: "UYU", symbol: "$U", name: "Uruguayan Peso" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  { code: "RSD", symbol: "din.", name: "Serbian Dinar" },
  { code: "BGN", symbol: "lv", name: "Bulgarian Lev" },
  { code: "RON", symbol: "lei", name: "Romanian Leu" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { code: "ALL", symbol: "L", name: "Albanian Lek" },
  { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "MKD", symbol: "den", name: "Macedonian Denar" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tugrik" },
  { code: "UZS", symbol: "soʻm", name: "Uzbekistani Som" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
  { code: "XPF", symbol: "CFP", name: "CFP Franc" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
  { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
  { code: "BWP", symbol: "P", name: "Botswana Pula" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { code: "MUR", symbol: "Rs", name: "Mauritian Rupee" },
  { code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { code: "WST", symbol: "WS$", name: "Samoan Tālā" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { code: "BMD", symbol: "BD$", name: "Bermudian Dollar" },
  { code: "BSD", symbol: "B$", name: "Bahamian Dollar" },
  { code: "BBD", symbol: "Bds$", name: "Barbadian Dollar" },
  { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  { code: "TTD", symbol: "TT$", name: "Trinidad & Tobago Dollar" },
  { code: "XCD", symbol: "EC$", name: "East Caribbean Dollar" },
  { code: "AWG", symbol: "Afl.", name: "Aruban Florin" },
  { code: "ANG", symbol: "NAƒ", name: "Netherlands Antillean Guilder" },
  { code: "HTG", symbol: "G", name: "Haitian Gourde" },
  { code: "GYD", symbol: "G$", name: "Guyanese Dollar" },
  { code: "SRD", symbol: "Sr$", name: "Surinamese Dollar" },
  { code: "BZD", symbol: "BZ$", name: "Belize Dollar" },
  { code: "KYD", symbol: "CI$", name: "Cayman Islands Dollar" },
  { code: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
  { code: "BND", symbol: "B$", name: "Brunei Dollar" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { code: "LAK", symbol: "₭", name: "Lao Kip" },
  { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
  { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { code: "CVE", symbol: "Esc", name: "Cape Verdean Escudo" },
  { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc" },
  { code: "LRD", symbol: "L$", name: "Liberian Dollar" },
  { code: "LSL", symbol: "L", name: "Lesotho Loti" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
  { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya" },
  { code: "NAD", symbol: "N$", name: "Namibian Dollar" },
  { code: "SCR", symbol: "SR", name: "Seychellois Rupee" },
  { code: "SLE", symbol: "Le", name: "Sierra Leonean Leone" },
  { code: "SOS", symbol: "Sh.So.", name: "Somali Shilling" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound" },
  { code: "STN", symbol: "Db", name: "São Tomé & Príncipe Dobra" },
  { code: "SZL", symbol: "E", name: "Eswatini Lilangeni" },
  { code: "SYP", symbol: "LS", name: "Syrian Pound" },
  { code: "TJS", symbol: "SM", name: "Tajikistani Somoni" },
  { code: "TMT", symbol: "T", name: "Turkmenistani Manat" },
  { code: "VUV", symbol: "VT", name: "Vanuatu Vatu" },
  { code: "YER", symbol: "﷼", name: "Yemeni Rial" },
  { code: "ZWL", symbol: "Z$", name: "Zimbabwean Dollar" }
];

// Approximate benchmark exchange rates relative to 1.00 USD
export const USD_EXCHANGE_RATES = {
  USD: 1.0,
  EUR: 0.92,
  GBP: 0.78,
  JPY: 155.0,
  CAD: 1.36,
  AUD: 1.52,
  CHF: 0.90,
  CNY: 7.24,
  CNH: 7.25,
  INR: 83.5,
  BRL: 5.42,
  RUB: 88.0,
  ZAR: 18.2,
  MXN: 18.1,
  SGD: 1.35,
  NZD: 1.64,
  HKD: 7.81,
  SEK: 10.6,
  NOK: 10.7,
  KRW: 1380.0,
  TRY: 32.8,
  AED: 3.67,
  SAR: 3.75,
  THB: 36.5,
  IDR: 16400.0,
  MYR: 4.71,
  PHP: 58.5,
  VND: 25400.0,
  PLN: 4.0,
  EGP: 47.8,
  CLP: 940.0,
  COP: 4100.0,
  PEN: 3.75,
  PKR: 278.0,
  NGN: 1520.0,
  KES: 129.0,
  GHS: 15.2,
  ARS: 925.0,
  ILS: 3.72,
  DKK: 6.88,
  HUF: 365.0,
  CZK: 23.2,
  TWD: 32.5,
  QAR: 3.64,
  KWD: 0.307,
  BHD: 0.376,
  OMR: 0.385,
  JOD: 0.709,
  DZD: 134.0,
  MAD: 9.95,
  TND: 3.12,
  LBP: 89500.0,
  IQD: 1310.0,
  BDT: 117.0,
  LKR: 304.0,
  NPR: 133.0,
  CRC: 525.0,
  DOP: 59.0,
  GTQ: 7.75,
  UYU: 39.5,
  BOB: 6.9,
  PYG: 7500.0,
  HNL: 24.7,
  NIO: 36.8,
  PAB: 1.0,
  RSD: 108.0,
  BGN: 1.80,
  RON: 4.58,
  ISK: 138.0,
  GEL: 2.80,
  AMD: 388.0,
  AZN: 1.70,
  KZT: 465.0,
  UAH: 40.5,
  ALL: 92.5,
  BAM: 1.80,
  MKD: 56.5,
  MNT: 3450.0,
  UZS: 12600.0,
  XOF: 603.0,
  XAF: 603.0,
  XPF: 110.0,
  ETB: 57.5,
  TZS: 2620.0,
  UGX: 3750.0,
  RWF: 1310.0,
  BWP: 13.5,
  ZMW: 25.5,
  MZN: 63.8,
  AOA: 855.0,
  MUR: 46.5,
  FJD: 2.25,
  PGK: 3.88,
  WST: 2.70,
  TOP: 2.35,
  BMD: 1.0,
  BSD: 1.0,
  BBD: 2.0,
  JMD: 156.0,
  TTD: 6.78,
  XCD: 2.70,
  AWG: 1.80,
  ANG: 1.80,
  HTG: 132.0,
  GYD: 209.0,
  SRD: 31.5,
  BZD: 2.0,
  KYD: 0.83,
  MOP: 8.05,
  BND: 1.35,
  MMK: 2100.0,
  KHR: 4100.0,
  LAK: 21800.0,
  MVR: 15.4,
  AFN: 70.5,
  CVE: 101.5,
  DJF: 178.0,
  ERN: 15.0,
  GMD: 68.0,
  GNF: 8600.0,
  LRD: 194.0,
  LSL: 18.2,
  MGA: 4500.0,
  MWK: 1730.0,
  MRU: 39.8,
  NAD: 18.2,
  SCR: 13.6,
  SLE: 22.5,
  SOS: 571.0,
  SSP: 1550.0,
  STN: 22.5,
  SZL: 18.2,
  SYP: 13000.0,
  TJS: 10.7,
  TMT: 3.5,
  VUV: 120.0,
  YER: 250.0,
  ZWL: 25.0
};

// Helper to get currency symbol by code
export function getCurrencySymbol(code = "USD") {
  const found = WORLD_CURRENCIES.find(
    (c) => c.code.toUpperCase() === String(code).toUpperCase()
  );
  return found ? found.symbol : "$";
}

// Helper to format currency display option text
export function getCurrencyLabel(c) {
  return `${c.code} (${c.symbol}) — ${c.name}`;
}

/**
  * Converts an amount from a captured source currency to the Default Accounting Currency.
  * @param {number} amount - Amount in source currency
  * @param {string} fromCurrency - Captured source currency code (e.g. "EUR")
  * @param {string} toCurrency - Default Accounting Currency code (e.g. "USD")
  * @returns {{
  *   convertedAmount: number,
  *   exchangeRate: number,
  *   fromCurrency: string,
  *   toCurrency: string,
  *   isConverted: boolean
  * }}
  */
export function convertCurrency(amount, fromCurrency = "USD", toCurrency = "USD") {
  const numericAmount = parseFloat(amount) || 0;
  const src = (fromCurrency || "USD").toUpperCase();
  const target = (toCurrency || "USD").toUpperCase();

  if (src === target) {
    return {
      convertedAmount: numericAmount,
      exchangeRate: 1.0,
      fromCurrency: src,
      toCurrency: target,
      isConverted: false
    };
  }

  const rateSrcToUSD = USD_EXCHANGE_RATES[src] || 1.0;
  const rateTargetToUSD = USD_EXCHANGE_RATES[target] || 1.0;

  // Convert src -> USD -> target
  // e.g. 100 EUR to USD: 100 / 0.92 = 108.70 USD
  // 108.70 USD to GBP: 108.70 * 0.78 = 84.78 GBP
  const rateSrcToTarget = (1 / rateSrcToUSD) * rateTargetToUSD;
  const converted = numericAmount * rateSrcToTarget;

  return {
    convertedAmount: Math.round(converted * 100) / 100,
    exchangeRate: Math.round(rateSrcToTarget * 10000) / 10000,
    fromCurrency: src,
    toCurrency: target,
    isConverted: true
  };
}
